### ISSUE TITLE
Example usage?

### ISSUE THREAD

**Issue by mhulse** [mcfitz2/streetview#1]
Just curious if you could provide a simple usage example?

Thanks!

**Comment by mcfitz2** [comment]
It's pretty straightforward since both functions take the same params as the reference API, but I've added an example in the README to clear things up.

**Comment by mhulse** [comment]
Thanks @mcfitz2, I really appreciate it. Nice work on this, btw. Nice to see your approach here; it's more simple than other projects I've seen.
